/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package blog;

/**
 *
 * @author Esadc
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_blogYaz = new javax.swing.JButton();
        b_bloglarım = new javax.swing.JButton();
        b_tBloglar = new javax.swing.JButton();
        l_label1 = new javax.swing.JLabel();
        b_logOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b_blogYaz.setText("Blog Yaz");
        b_blogYaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_blogYazActionPerformed(evt);
            }
        });

        b_bloglarım.setText("Bloglarım");
        b_bloglarım.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_bloglarımActionPerformed(evt);
            }
        });

        b_tBloglar.setText("Tüm Bloglar");
        b_tBloglar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tBloglarActionPerformed(evt);
            }
        });

        l_label1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        l_label1.setText("ANA MENÜ");

        b_logOut.setText("Çıkış Yap");
        b_logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_logOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(b_tBloglar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b_bloglarım, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_blogYaz, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(l_label1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 162, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(b_logOut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(139, Short.MAX_VALUE)
                        .addComponent(b_blogYaz))
                    .addComponent(l_label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addComponent(b_bloglarım)
                .addGap(55, 55, 55)
                .addComponent(b_tBloglar)
                .addGap(33, 33, 33)
                .addComponent(b_logOut)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_blogYazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_blogYazActionPerformed
        // TODO add your handling code here:
        dispose();
        WriteBlogFrame w=new WriteBlogFrame();
        w.setVisible(true);
    }//GEN-LAST:event_b_blogYazActionPerformed

    private void b_bloglarımActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_bloglarımActionPerformed
        // TODO add your handling code here:
        dispose();
        MyBlogsFrame w1=new MyBlogsFrame();
        w1.setVisible(true);
    }//GEN-LAST:event_b_bloglarımActionPerformed

    private void b_tBloglarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tBloglarActionPerformed
        // TODO add your handling code here:
        dispose();
        AllBlogsFrame w2=new AllBlogsFrame();
        w2.setVisible(true);
    }//GEN-LAST:event_b_tBloglarActionPerformed

    private void b_logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_logOutActionPerformed
        dispose();
        LoginFrame lf=new LoginFrame();
        lf.setVisible(true);
    }//GEN-LAST:event_b_logOutActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_blogYaz;
    private javax.swing.JButton b_bloglarım;
    private javax.swing.JButton b_logOut;
    private javax.swing.JButton b_tBloglar;
    private javax.swing.JLabel l_label1;
    // End of variables declaration//GEN-END:variables
}
